-- Seed les types d'activités historiques dans category_colors
-- (pattern unifié avec inventory/suppliers/staff — cf. migration 008).
INSERT OR IGNORE INTO category_colors (module, name, color, bg, label) VALUES
  ('activities', 'atelier_creatif',    '#7C3AED', '#F5F3FF', 'Atelier créatif'),
  ('activities', 'musique',             '#1E40AF', '#EFF6FF', 'Musique'),
  ('activities', 'jeux',                '#059669', '#ECFDF5', 'Jeux'),
  ('activities', 'sortie',              '#D97706', '#FFFBEB', 'Sortie'),
  ('activities', 'sport',               '#0F766E', '#F0FDFA', 'Sport / Motricité'),
  ('activities', 'lecture',             '#8B5CF6', '#F5F3FF', 'Lecture'),
  ('activities', 'cuisine',             '#EA580C', '#FFF7ED', 'Cuisine'),
  ('activities', 'bien_etre',           '#EC4899', '#FDF2F8', 'Bien-être'),
  ('activities', 'intergenerationnel',  '#0EA5E9', '#F0F9FF', 'Intergénérationnel'),
  ('activities', 'fete',                '#DC2626', '#FEF2F2', 'Fête / Événement'),
  ('activities', 'cognitive',           '#10B981', '#ECFDF5', 'Cognitif'),
  ('activities', 'boardgames',          '#059669', '#ECFDF5', 'Jeux de société'),
  ('activities', 'creative',            '#7C3AED', '#F5F3FF', 'Créatif'),
  ('activities', 'music',               '#1E40AF', '#EFF6FF', 'Musique'),
  ('activities', 'food',                '#EA580C', '#FFF7ED', 'Cuisine'),
  ('activities', 'social',              '#0EA5E9', '#F0F9FF', 'Social'),
  ('activities', 'outing',              '#D97706', '#FFFBEB', 'Sortie'),
  ('activities', 'festive',             '#DC2626', '#FEF2F2', 'Fête'),
  ('activities', 'sensory',             '#EC4899', '#FDF2F8', 'Sensoriel'),
  ('activities', 'reading',             '#8B5CF6', '#F5F3FF', 'Lecture'),
  ('activities', 'press',               '#8B5CF6', '#F5F3FF', 'Presse'),
  ('activities', 'volleyball',          '#0F766E', '#F0FDFA', 'Volley'),
  ('activities', 'vr',                  '#6366F1', '#EEF2FF', 'VR / Réalité virtuelle'),
  ('activities', 'animal',              '#92400E', '#FEF3C7', 'Médiation animale'),
  ('activities', 'religious',           '#475569', '#F1F5F9', 'Culte'),
  ('activities', 'cinema',              '#1E293B', '#F1F5F9', 'Cinéma'),
  ('activities', 'other',               '#64748B', '#F1F5F9', 'Autre');
